#!/bin/bash
#run datasets using Sequential Algorithms

prange=100000
krange=10
DNA="DNA"
Point="Point"
data="data/"
result="result/"
k="k"
p="p"
txt=".txt"
out=".out"

echo "Running Point datasets ..."
for (( i=2; i<=$krange; i++ ))
do 
	echo "runnig 2D datasets for k=$i"
	for ((j=10; j<=$prange; j*=10))
	do
		python PointSequential.py -k $i -e 0.0001 -i $data$Point$k$i$p$j$txt -o $result$Point$k$i$p$j$out
	done
done

echo "Running DNA datasets..."
for (( i=2; i<=$krange; i++ ))
do 
	echo "running DNA datasets for k=$i"
	for ((j=10; j<=$prange; j*=10))
	do
		python DNASequential.py -k $i -e 0.0001 -i $data$DNA$k$i$p$j$txt -o $result$DNA$k$i$p$j$out
	done
done